<?php
return [
    'urls' => [
        'launch' => rtrim(env('LAUNCH_URL', 'https://launch.huggg.me/'), '/'),
        'images' => rtrim(env('APP_IMAGE_URL', 'https://cdn.huggg.me'), '/'),
        'download' => rtrim(env('DOWNLOAD_APP_URL', 'https://api.huggg.me/download'), '/'),
    ],

    'goldenHuggg' => [
        'perUser' => env('GOLDEN_HUGGG_PER_USER', 5),
        'productId' => env('GOLDEN_HUGGG_PRODUCT_ID', ''),
        'expiryHours' => env('GOLDEN_HUGGG_EXPIRY_HOURS', 36),
        // copy-paste from above as we can't use config() calls in this context and I want a full URL
        'imageUrl' => env('GOLDEN_HUGGG_IMAGE', rtrim(env('APP_IMAGE_URL', 'https://cdn.huggg.me'), '/') . '/golden-huggg-sticker.png')
    ],

    'regex' => [
        'uuid' => '/^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i',
        'shortCode' => '^([0-9A-Za-z]){15}$',
    ],

    'wotds' => [
        'j' => [
            'jack',
            'jump',
            'juice',
            'javelin',
            'jam',
            'joy',
            'jolly',
            'jingle',
            'jelly',
            'jackpot',
            'jellyfish',
            'jokes',
            'jupiter',
            'jockey',
            'jumbo',
            'jewel',
            'jetpack',
            'jog',
            'jazz',
        ],
        'f' => [
            'fox',
            'fruit',
            'fantastic',
            'fish',
            'fancy',
            'fossil',
            'future',
            'feel',
            'faith',
            'fast',
            'favourite',
            'field',
            'fabric',
            'feather',
            'fabulous',
            'freddo',
        ],
        'm' => [
            'market',
            'metal',
            'modern',
            'menu',
            'music',
            'mayor',
            'maths',
            'monkey',
            'minion',
            'magic',
            'match',
        ],
        'a' => [
            'apple',
            'achieve',
            'affection',
            'amazing',
            'angel',
            'awesome',
        ],
        's' => [
            'shine',
            'sky',
            'smart',
            'smile',
            'song',
            'splendid',
            'success',
            'sun',
            'sunlight',
            'sunshine',
            'super',
            'sweet',
        ],
        'o' => [
            'optimism',
            'orange',
            'oblong',
            'ostrich',
        ],
        'n' => [
            'nice',
            'noon',
            'note',
            'number',
            'nudge',
            'north',
            'ninja',
            'noise',
            'new',
            'navy',
            'nifty',
            'night',
            'nurse',
            'nylon',
            'natural',
            'nature',
            'norway',
        ],
        'd' => [
            'delicious',
            'delight',
            'diamond',
            'disco',
            'dance',
            'donkey'
        ],
    ],
];
